apiVersion: v1
kind: Service
metadata:
  name: flexcub-private-service
  namespace: flexcub-testing
status:
  loadBalancer: {}
spec:
  ports:
    - name: flexcub-private-service
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: flexcub-private-api
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
 
